pub struct x64_regs {
    r15       : libc::uint64_t,
    r14       : libc::uint64_t,
    r13       : libc::uint64_t,
    r12       : libc::uint64_t,
    rbp       : libc::uint64_t,
    rbx       : libc::uint64_t,
    r11       : libc::uint64_t,
    r10       : libc::uint64_t,
    r9        : libc::uint64_t,
    r8        : libc::uint64_t,
    rax       : libc::uint64_t,
    rcx       : libc::uint64_t,
    rdx       : libc::uint64_t,
    rsi       : libc::uint64_t,
    rdi       : libc::uint64_t,
    orig_rax  : libc::uint64_t,
    rip       : libc::uint64_t,
    cs        : libc::uint64_t,
    eflags    : libc::uint64_t,
    rsp       : libc::uint64_t,
    ss        : libc::uint64_t,
    fs_base   : libc::uint64_t,
    gs_base   : libc::uint64_t,
    ds        : libc::uint64_t,
    es        : libc::uint64_t,
    fs        : libc::uint64_t,
    gs        : libc::uint64_t,
}

impl Default for x64_regs {
    fn default() -> x64_regs {
        x64_regs {
            r15       : 0,
            r14       : 0,
            r13       : 0,
            r12       : 0,
            rbp       : 0,
            rbx       : 0,
            r11       : 0,
            r10       : 0,
            r9        : 0,
            r8        : 0,
            rax       : 0,
            rcx       : 0,
            rdx       : 0,
            rsi       : 0,
            rdi       : 0,
            orig_rax  : 0,
            rip       : 0,
            cs        : 0,
            eflags    : 0,
            rsp       : 0,
            ss        : 0,
            fs_base   : 0,
            gs_base   : 0,
            ds        : 0,
            es        : 0,
            fs        : 0,
            gs        : 0,
        }
    }
}